#!/bin/bash

# suppression des paquets live*
apt autoremove --purge -y live-boot live-tools live-config live-config-systemd calamares-settings-debian calamares

# décommenter pour activer os-prober
sed -i '/OS_PROBER/s/^#//g' /etc/default/grub
update-grub

exit 0
